branches:
  # whitelist
  only:
    - master

image: Visual Studio 2017

install:
- ps: (new-object Net.WebClient).DownloadString("https://raw.github.com/dzimchuk/ExtensionScripts/master/AppVeyor/vsix.ps1") | iex

before_build:
  - ps: Vsix-IncrementVsixVersion | Vsix-UpdateBuildVersion
  - ps: Vsix-TokenReplacement ExperimentalTools.Vsix\source.extension.cs 'Version = "([0-9\\.]+)"' 'Version = "{version}"'

build_script:
  - dotnet --info
  - dotnet restore
  - nuget restore -Verbosity quiet
  - msbuild /p:configuration=Release /p:DeployExtension=false /p:ZipPackageCompressionLevel=normal /v:m

test_script:
  - dotnet test -c Release ExperimentalTools.Tests
   
after_test:
  - ps: Vsix-PushArtifacts -path .\ExperimentalTools.Vsix\bin\Release\*.vsix -publishToGallery
