branches:
  # whitelist
  only:
    - master

image: Visual Studio 2019

install:
- ps: (new-object Net.WebClient).DownloadString("https://raw.github.com/madskristensen/ExtensionScripts/master/AppVeyor/vsix.ps1") | iex

build_script:
  - dotnet --info
  - dotnet restore
  - nuget restore -Verbosity quiet
  - msbuild /p:configuration=Release /p:DeployExtension=false /p:ZipPackageCompressionLevel=normal /v:m

test_script:
  - dotnet test -c Release ExperimentalTools.Tests
   
after_test:
  - ps: Vsix-PushArtifacts -path .\ExperimentalTools.Vsix\bin\Release\*.vsix -publishToGallery
