// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.211
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ExperimentalTools.Vsix
{
    static class Vsix
    {
        public const string Id = "fe00c281-eed0-4c6e-901b-d8b845c82e35";
        public const string Name = "Experimental Tools 2017";
        public const string Description = @"A bunch of quality refactorings and code fixes that are going to improve your C# development experience in Visual Studio and remove some common pain.";
        public const string Language = "en-US";
        public const string Version = "1.2";
        public const string Author = "Andrei Dzimchuk";
        public const string Tags = "Refactoring, Roslyn, Productivity, Coding, C#, CSharp";
    }
}
