// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ExperimentalTools.Vsix
{
    internal sealed partial class Vsix
    {
        public const string Id = "4ea21f37-c749-42cc-9e24-7dfc4d26fca5";
        public const string Name = "Experimental Tools";
        public const string Description = @"A bunch of quality refactorings and code fixes that are going to improve your C# development experience in Visual Studio and remove some common pain.";
        public const string Language = "en-US";
        public const string Version = "2.0.0";
        public const string Author = "Andrei Dzimchuk";
        public const string Tags = "Refactoring, Roslyn, Productivity, Coding, C#, CSharp";
    }
}
