//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExperimentalTools.Localization {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExperimentalTools.Localization.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add constructor and initialize field.
        /// </summary>
        internal static string AddConstructorAndInitializeField {
            get {
                return ResourceManager.GetString("AddConstructorAndInitializeField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add initialized field.
        /// </summary>
        internal static string AddInitializedField {
            get {
                return ResourceManager.GetString("AddInitializedField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naming.
        /// </summary>
        internal static string CategoryNaming {
            get {
                return ResourceManager.GetString("CategoryNaming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is constructor.
        /// </summary>
        internal static string FixConstructorName {
            get {
                return ResourceManager.GetString("FixConstructorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialize existing field.
        /// </summary>
        internal static string InitializeExistingField {
            get {
                return ResourceManager.GetString("InitializeExistingField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialize field in existing constructor.
        /// </summary>
        internal static string InitializeFieldInExistingConstructor {
            get {
                return ResourceManager.GetString("InitializeFieldInExistingConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialize field in existing constructors.
        /// </summary>
        internal static string InitializeFieldInExistingConstructors {
            get {
                return ResourceManager.GetString("InitializeFieldInExistingConstructors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namespace &apos;{0}&apos; does not match file path.
        /// </summary>
        internal static string NamespaceNormalizationAnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("NamespaceNormalizationAnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namespace does not match file path.
        /// </summary>
        internal static string NamespaceNormalizationAnalyzerTitle {
            get {
                return ResourceManager.GetString("NamespaceNormalizationAnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename &apos;{0}&apos; to &apos;{1}&apos;.
        /// </summary>
        internal static string RenameAToB {
            get {
                return ResourceManager.GetString("RenameAToB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To internal.
        /// </summary>
        internal static string ToInternal {
            get {
                return ResourceManager.GetString("ToInternal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To internal (explicit).
        /// </summary>
        internal static string ToInternalExplicit {
            get {
                return ResourceManager.GetString("ToInternalExplicit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To internal (implicit).
        /// </summary>
        internal static string ToInternalImplicit {
            get {
                return ResourceManager.GetString("ToInternalImplicit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To private (explicit).
        /// </summary>
        internal static string ToPrivateExplicit {
            get {
                return ResourceManager.GetString("ToPrivateExplicit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To private (implicit).
        /// </summary>
        internal static string ToPrivateImplicit {
            get {
                return ResourceManager.GetString("ToPrivateImplicit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To protected.
        /// </summary>
        internal static string ToProtected {
            get {
                return ResourceManager.GetString("ToProtected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To protected internal.
        /// </summary>
        internal static string ToProtectedInternal {
            get {
                return ResourceManager.GetString("ToProtectedInternal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To public.
        /// </summary>
        internal static string ToPublic {
            get {
                return ResourceManager.GetString("ToPublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type name &apos;{0}&apos; does not match file name.
        /// </summary>
        internal static string TypeAndDocumentNameAnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("TypeAndDocumentNameAnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type name does not match file name.
        /// </summary>
        internal static string TypeAndDocumentNameAnalyzerTitle {
            get {
                return ResourceManager.GetString("TypeAndDocumentNameAnalyzerTitle", resourceCulture);
            }
        }
    }
}
